techosoft/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

/*USER MANAGEMENT*/
// Route::resource('/clients', 'Admin\User\UserController');
Route::resource('/staff', 'Admin\User\StaffController');
Route::resource('/client', 'Admin\User\ClientController');

/*CATEGORY MANAGEMENT*/
Route::resource('/primary', 'Admin\Category\PrimaryController');
Route::resource('/parent', 'Admin\Category\ParentController');
Route::resource('/child', 'Admin\Category\ChildController');
Route::get('/child/get_parent/{id}','Admin\Category\ChildController@get_parent');
/*END CATEGORY*/

/*SITE CONFIG*/
Route::resource('/settings', 'Admin\Setting\SettingController');

/*PAGE MANAGEMENT*/
Route::resource('/page', 'Admin\Page\PageController');

/*PAGE MANAGEMENT*/
Route::resource('/service', 'Admin\Services\ServiceController');
Route::get('get/child/{id}','Admin\Services\ServiceController@get_child');

/*PROJECT MANAGEMENT*/
Route::resource('techosoft_service', 'Admin\Project\ServiceController');
Route::resource('project', 'Admin\Project\ProjectController');
Route::get('project/add_new_phase/{id}', 'Admin\Project\ProjectController@add_new_phase');
Route::post('project/store_new_phase/{id}', 'Admin\Project\ProjectController@store_new_phase');
Route::get('change/status/{id}/{status}', 'Admin\Project\ProjectController@update_status');
Route::get('edit_phase/{phase_id}', 'Admin\Project\ProjectController@edit_phase');
Route::get('delete/doc/{id}', 'Admin\Project\ProjectController@delete_doc');

/*ORDER MANAGEMENT*/
Route::resource('order', 'Admin\Order\OrderController');

/*BILL MANAGEMENT*/
Route::resource('bill', 'Admin\Bill\BillController');
Route::get('ajax/get/order_id/{id}', 'Admin\Bill\BillController@get_order');



/*Dark mode route*/
Route::get('/darkmode/status', 'Other\CommonController@darkmode')->name('darkmode.status');














// COURSE MANAGEMENT
Route::get('/step_first', 'Admin\Course\CourseController@step_first')->name('step_first');
Route::get('/upload/course', 'Admin\Course\CourseController@upload_course')->name('upload_course');

techosoft/app/Http/Controllers/Admin/Project/ProjectController.php
<?php

namespace App\Http\Controllers\Admin\Project;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Project\Service;
use App\Model\Project\Project;
use App\Model\Project\Order;
use App\Model\Project\ProjectServices;
use App\Model\Project\ProjectDocuments;
use App\User;
use Session; 
use DB; 

class ProjectController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::withTrashed()->get();
        return view('admin.project.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // get client from user table and fetch to create project view
        $clients = User::where('role_id', 2)->get();
        $services = Service::get();
        return view('admin.project.create', compact('clients', 'services'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
                            'project_name'       => 'required',
                            'client_id'          => 'required',
                            'services'           => 'required',
                            'srs'                => 'required',
                            'amount'             => 'required',
                            'referral_incentive' => 'required',
                            'timeline'           => 'required',
                            'doc'                => 'required',
        ]);

        // status: 1 Pending, 2 Working, 3 Hold, 4 Cancel, 5 Complete 
        // insert new project
        $store_project = Project::create([
                                        'client_id'    =>$request->client_id,
                                        'project_name' =>$request->project_name,
                                        'status'       =>1,
                                         ]);

        // insert in project's details order
        $store_project_details = Order::create([
                                            'project_id'          => $store_project->id,
                                            'srs'                 => $request->srs,
                                            'amount'              => $request->amount,
                                            'referral_incentive'  => $request->referral_incentive,
                                            'timeline'            => $request->timeline,
                                            ]);

        // insert order_id in Order table
        $store_order = Order::where('id', $store_project_details->id)->update([
                                    'order_id'   => 'TT000'.$store_project_details->id,
                                    ]);


        // insert project's services
        $servcies = $request->services;
        for($i=0; $i<count($servcies); $i++){
            $store_service = ProjectServices::create([
                                                    'project_id'  => $store_project->id,
                                                    'service_id'  => $servcies[$i],
                                                    ]);
        }
        // insert project's document
        foreach($request->doc as $document){
            $doc_name  =strtotime(date('Y-m-d H:i:s')).'_'.$document->getClientOriginalName();
            $document->move('img/project', $doc_name);
            $store_document  = ProjectDocuments::create([
                                                        'project_id'     => $store_project->id,
                                                        'order_id'       => $store_project_details->id,
                                                        'document_name'  => $doc_name,
                                                        ]);
        }
            
        Session::flash('success', 'Project Created Successfully');
        return redirect()->route('project.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // dd($id);     
        $orders   = Order::where('project_id', $id)->get();
        $details  = Order::where('project_id', $id)->first();
        // $data     = $details->project->pro_service;

        $subscribe_service  = DB::table('project_services')->join('techosoft_services','techosoft_services.id','=','project_services.service_id')
                                                 ->where('project_id',$id)
                                                 ->get();

        $selected_service  = DB::table('project_services')->join('techosoft_services','techosoft_services.id','=','project_services.service_id')
                                                 ->where('project_id',$id)
                                                 ->pluck('techosoft_services.id');
                                                
                                                 // dd($selected_service);

        $unselected_services = Service::whereNotIn('id', $selected_service)->get();


        return view('admin.project.view_project_details', compact('orders', 'subscribe_service', 'details', 'unselected_services'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $orders   = Order::where('project_id', $id)->get();
        $project = Project::find($id);

        return view('admin.project.view_edit', compact('orders', 'project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate([
                            'srs'                => 'required',
                            'amount'             => 'required',
                            'referral_incentive' => 'required',
                            'timeline'           => 'required',
        ]);
        // $phase_data = Order::where('id', $id)->first();
        // dd($phase_data);

        $phase_data = Order::where('id', $id)->first();
        // dd($phase_data);
        if(isset($request->doc)){
            // Update in project's details
            $store_project_details = Order::where('id', $id)
                                            ->update([
                                                    'srs'                 => $request->srs,
                                                    'amount'              => $request->amount,
                                                    'referral_incentive'  => $request->referral_incentive,
                                                    'timeline'            => $request->timeline,
                                                    ]);



            // insert project's document
            foreach($request->doc as $document){
                $doc_name  =strtotime(date('Y-m-d H:i:s')).'_'.$document->getClientOriginalName();
                $document->move('img/project', $doc_name);
                $store_document  = ProjectDocuments::create([
                                                            'project_id'    => $phase_data->project_id,
                                                            'order_id'      => $phase_data->id,
                                                            'document_name' => $doc_name,
                                                            ]);
            }
            
            Session::flash('success', 'Phase Updated Successfully');
            return redirect()->route('project.edit',$phase_data->project_id);
        }
        else{
            // Update in project's details
            $store_project_details = Order::where('id', $id)
                                            ->update([
                                                    'srs'                 => $request->srs,
                                                    'amount'              => $request->amount,
                                                    'referral_incentive'  => $request->referral_incentive,
                                                    'timeline'            => $request->timeline,
                                                    ]);

            Session::flash('success', 'Phase Updated Successfully');
            return redirect()->route('project.edit',$phase_data->project_id);
            }
      
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /*Function is use to view create new phase blade file*/
    public function add_new_phase($id)
    {
        $project = Project::find($id);
        return view('admin.project.add_new_phase', compact('project'));
    }

    /*Funciton used to store new project phase*/
    public function store_new_phase(request $request, $id){
       
        $request->validate([
                            'srs'                => 'required',
                            'amount'             => 'required',
                            'referral_incentive' => 'required',
                            'timeline'           => 'required',
                            'doc'                => 'required',
        ]);

        // insert in project's details
        $store_project_details = Order::create([
                                            'project_id'          => $id,

techosoft/app/Http/Controllers/Admin/Project/ServiceController.php
<?php

namespace App\Http\Controllers\Admin\Project;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Project\Service;
use Session;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::withTrashed()->paginate(5);
        return view('admin.project.service.index', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['title'=>'required']);

        $insert = Service::create([
                                    'title'=> $request->title,
                                    'sac_code' =>$request->sac_code,
                                  ]);
        Session::flash('success','Service Added Successfully');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // DELTE METHOD CALL IN THIS FUNCTION
        $get_service = Service::where('id',$id)->withTrashed()->first();

        if(is_null($get_service->deleted_at)){
            $delete = Service::where('id',$id)->delete();
        }
        else{
            $restore = Service::where('id', $id)->restore();
        }
        return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(['title'=>'required']);

        $update = Service::where('id',$id)->update([
                                                    'title'=> $request->title,
                                                    'sac_code' =>$request->sac_code,
                                                   ]);
        Session::flash('success','Service Updated Successfully');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

techosoft/resources/views/admin/project/service/index.blade.php
@extends('layouts.app')
@section('title', 'User Mangement')
@section('breadcrumb')

   
	  <!--  BEGIN NAVBAR  -->
    <div class="sub-header-container">
        <header class="header navbar navbar-expand-sm">
            <a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg></a>

            <ul class="navbar-nav flex-row">
                <li>
                    <div class="page-header">

                        <nav class="breadcrumb-one" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0);"> Project Management</a></li>
                                <li class="breadcrumb-item"><a href="javascript:void(0);">Service</a></li>
                            </ol>
                        </nav>
                    </div>
                </li>  
            </ul>
        </header>
    </div>
    <!--  END NAVBAR  -->
    

@endsection

@section('content')

<div class="main-content">
   <div class="col-12">
      <div class="container">
         <div class="row">
            <div id="flStackForm" class="col-md-4 layout-spacing layout-top-spacing">
               <div class="statbox widget box box-shadow">
                  <div class="widget-header">
                     <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                           <h4>Add Service</h4>
                        </div>
                     </div>
                  </div>
                  <div class="widget-content widget-content-area">
                     <form method="post" action="{{route('techosoft_service.store')}}" method="post">
                        @csrf
                        @method('POST')
                        <div class="form-group mb-3">
                       <!--    <label>Service Title</label> -->
                          <input type="text" class="form-control" name="title"  placeholder="Service Name">
                          <br>
                        <!--   <label>SAC Code</label> -->
                          <input type="text" class="form-control" name="sac_code"  placeholder="SAC Code">
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Submit</button>
                     </form>
                  </div>
               </div>
            </div>

            <div id="flStackForm" class="col-md-8 layout-spacing layout-top-spacing">
               <div class="statbox widget box box-shadow">
                  <div class="widget-header">
                     <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                           <h4>Primary Categories List</h4>
                        </div>
                     </div>
                  </div>
                  <div class="widget-content widget-content-area">
                     <table id="zero-config" class="table table-hover" style="width:100%">
                        <thead>
                           <tr>
                              <th>Sr no.</th>
                              <th>Service</th>
                              <th>Sac Code</th>
                              <th>Status</th>
                              <th>Action</th>
                           </tr>
                        </thead>
                        <tbody>
                                @php $count=1; @endphp
                                @foreach($services as $data)
                            <tr>
                                <td>{{$count++}}</td>
                                <td>{{$data->title}}</td>
                                 <td>{{$data->sac_code}}</td>
                                <td>
                                    @if(is_null($data->deleted_at))
                                       <span><strong>Active</strong></span>
                                    @else
                                       <span style="color: red;"><strong>Inactive</strong></span>
                                    @endif
                                </td>
                                <td>
                                 <a  data-toggle="modal" data-target="#primary{{$data->id}}"><i data-feather="edit" style="color: blue; margin-right:5px;"></i></a>

                                <!-- Soft Delete -->
                                <a class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" href="{{route('techosoft_service.show',$data->id)}}" data-confirm="Are you sure you want to delete this?">
                                    @if(is_null($data->deleted_at))
                                       <i data-feather="toggle-right" style="color: green;"></i>
                                    @else
                                       <i data-feather="toggle-left" style="color: red;"></i>
                                    @endif

                                  </a>


                                </td>

                              <!-- Modal -->
                              <div class="modal fade" id="primary{{$data->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                 <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                       <form method="post" action="{{route('techosoft_service.update',$data->id)}}">
                                          <div class="modal-header">
                                             <h5 class="modal-title" id="exampleModalLabel">Edit Service</h5>
                                             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                             </button>
                                          </div>
                                          <div class="modal-body">
                                             @csrf
                                             @method('put')
                                             <div class="form-group mb-3">
                                                <input type="text" class="form-control" name="title" value="{{$data->title}}">
                                                <br>
                                                <input type="text" class="form-control" name="sac_code"  placeholder="SAC Code" value="{{$data->sac_code}}">

                                             </div>
                                          </div>
                                          <div class="modal-footer">
                                             <button class="btn" data-dismiss="modal"><i class="flaticon-cancel-12"></i> Discard</button>
                                             <button type="submit" class="btn btn-primary">Update</button>
                                          </div>
                                       </form>
                                    </div>
                                 </div>
                              </div>
                           </tr>
                          @endforeach
                        </tbody>
                     </table>
                     <div style="position: relative;margin-left: 40%;margin-right: 50%;">
                        {{ $services->links() }}
                    </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
   
@endsection