techosoft/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

/*USER MANAGEMENT*/
// Route::resource('/clients', 'Admin\User\UserController');
Route::resource('/staff', 'Admin\User\StaffController');
Route::resource('/client', 'Admin\User\ClientController');

/*CATEGORY MANAGEMENT*/
Route::resource('/primary', 'Admin\Category\PrimaryController');
Route::resource('/parent', 'Admin\Category\ParentController');
Route::resource('/child', 'Admin\Category\ChildController');
Route::get('/child/get_parent/{id}','Admin\Category\ChildController@get_parent');
/*END CATEGORY*/

/*SITE CONFIG*/
Route::resource('/settings', 'Admin\Setting\SettingController');

/*PAGE MANAGEMENT*/
Route::resource('/page', 'Admin\Page\PageController');

/*PAGE MANAGEMENT*/
Route::resource('/service', 'Admin\Services\ServiceController');
Route::get('get/child/{id}','Admin\Services\ServiceController@get_child');

/*PROJECT MANAGEMENT*/
Route::resource('techosoft_service', 'Admin\Project\ServiceController');
Route::resource('project', 'Admin\Project\ProjectController');
Route::get('project/add_new_phase/{id}', 'Admin\Project\ProjectController@add_new_phase');
Route::post('project/store_new_phase/{id}', 'Admin\Project\ProjectController@store_new_phase');
Route::get('change/status/{id}/{status}', 'Admin\Project\ProjectController@update_status');
Route::get('edit_phase/{phase_id}', 'Admin\Project\ProjectController@edit_phase');
Route::get('delete/doc/{id}', 'Admin\Project\ProjectController@delete_doc');

/*ORDER MANAGEMENT*/
Route::resource('order', 'Admin\Order\OrderController');

/*BILL MANAGEMENT*/
Route::resource('bill', 'Admin\Bill\BillController');
Route::get('ajax/get/order_id/{id}', 'Admin\Bill\BillController@get_order');



/*Dark mode route*/
Route::get('/darkmode/status', 'Other\CommonController@darkmode')->name('darkmode.status');














// COURSE MANAGEMENT
Route::get('/step_first', 'Admin\Course\CourseController@step_first')->name('step_first');
Route::get('/upload/course', 'Admin\Course\CourseController@upload_course')->name('upload_course');

techosoft/app/Http/Controllers/Admin/Project/ServiceController.php
<?php

namespace App\Http\Controllers\Admin\Project;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Project\Service;
use Session;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::withTrashed()->paginate(5);
        return view('admin.project.service.index', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['title'=>'required']);

        $insert = Service::create([
                                    'title'=> $request->title,
                                    'sac_code' =>$request->sac_code,
                                  ]);
        Session::flash('success','Service Added Successfully');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // DELTE METHOD CALL IN THIS FUNCTION
        $get_service = Service::where('id',$id)->withTrashed()->first();

        if(is_null($get_service->deleted_at)){
            $delete = Service::where('id',$id)->delete();
        }
        else{
            $restore = Service::where('id', $id)->restore();
        }
        return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(['title'=>'required']);

        $update = Service::where('id',$id)->update([
                                                    'title'=> $request->title,
                                                    'sac_code' =>$request->sac_code,
                                                   ]);
        Session::flash('success','Service Updated Successfully');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

techosoft/app/Http/Controllers/Admin/Services/ServiceController.php
<?php

namespace App\Http\Controllers\Admin\Services;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Services\Service;
use App\Model\Category\Primary;
use App\Model\Category\Child;
use Session;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::withTrashed()->get();
        return view('admin.services.index', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $primary_categorys = Primary::all();
        return view('admin.services.create', compact('primary_categorys'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
                                'primary_id'=>   'required',
                                'name'      =>   'required',
                                'content'   =>   'required',
                                'image'     =>   'required',
                           ]);

        $image = $request->image;
        $image_name  =strtotime(date('Y-m-d H:i:s')).'_'.$image->getClientOriginalName();
        $image->move('img/service', $image_name);

        $insert = Service::create([
                                'primary_id'          => $request->primary_id,
                                'parent_id'           => $request->parent_id,
                                'child_id'            => $request->child_id,
                                'meta_tag'            => $request->meta_tag,
                                'meta_description'    => $request->meta_description, 
                                'title'               => $request->name,
                                'content'             => $request->content,
                                'image'               => $image_name,
                               ]);
        Session::flash('success',$request->name. ' Service Page Added Successfully');
        return redirect()->route('service.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Service::where('id', $id)->withTrashed()->first();
        $primary_categorys = Primary::all();
        return view('admin.services.edit', compact('data','primary_categorys'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $get_page = Service::where('id',$id)->withTrashed()->first();
        if(is_null($get_page->deleted_at)){
            $delete = Service::where('id',$id)->delete();
        }
        else{
            $restore = Service::where('id', $id)->restore();
        }
        Session::flash('success', 'Service page Deleted Successfully');
        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
                            'primary_id'=>   'required',
                            'name'      =>   'required',
                            'content'   =>   'required',
                            ]);

        if(isset($request->image)){
            // get image
            $check_image = Service::where('id', $id)->first();
            // image path
            $image_path = 'img/service/'.$check_image->image;
            // if image exist delte image form database
            if(file_exists($image_path)){
              unlink($image_path);
            }
            $image       = $request->image;
            $image_name  =strtotime(date('Y-m-d H:i:s')).'_'.$image->getClientOriginalName();
            $image->move('img/service', $image_name);

            $update = Service::where('id',$id)
                            ->update([
                                    'meta_tag'          => $request->meta_tag,
                                    'meta_description'  => $request->meta_description, 
                                    'primary_id'        => $request->primary_id,
                                    'parent_id'         => $request->parent_id,
                                    'child_id'          => $request->child_id,
                                    'title'             => $request->name,
                                    'content'           => $request->content,
                                    'image'             => $image_name,
                                   ]);
        }
        else{
            $update = Service::where('id',$id)
                            ->update([
                                    'meta_tag'          => $request->meta_tag,
                                    'meta_description'  => $request->meta_description, 
                                    'primary_id'        => $request->primary_id,
                                    'parent_id'         => $request->parent_id,
                                    'child_id'          => $request->child_id,
                                    'title'             => $request->name,
                                    'content'           => $request->content,
                                   ]);

        }   
        Session::flash('success',$request->name. ' Service Updated Successfully');
        return redirect()->route('service.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function get_child($id){

        $data = Child::where('parent_id', $id)->get()->pluck('title', 'id');
        return Response()->json($data);
    }
}

techosoft/resources/views/admin/services/create.blade.php
@extends('layouts.app')
@section('title', 'CMS')
@section('breadcrumb')
	  <!--  BEGIN NAVBAR  -->
    <div class="sub-header-container">
        <header class="header navbar navbar-expand-sm">
            <a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg></a>

            <ul class="navbar-nav flex-row">
                <li>
                    <div class="page-header">

                        <nav class="breadcrumb-one" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0);"> CMS Management</a></li>
                                <li class="breadcrumb-item"><a href="javascript:void(0);"> Services Page</a></li>
                                <li class="breadcrumb-item"><a href="javascript:void(0);">Create Services Page</a></li>
                            </ol>
                        </nav>


                    </div>
                </li>  
            </ul>
            <ul class="navbar-nav flex-row ml-auto ">
                <li class="nav-item more-dropdown">
                    <div class="dropdown  custom-dropdown-icon">
                        <div class="col-lg-12">
                             <button form="add_page" type="submit" class="btn btn-outline-primary btn-rounded mb-2" value="Submit">Add Page</button>
                        </div>
                    </div>
                </li>
            </ul>
        </header>
    </div>
    <!--  END NAVBAR  -->
@endsection

@section('content')
      <!--  BEGIN CONTENT AREA  -->
        <div class="layout-px-spacing">                
                
            <div class="account-settings-container layout-top-spacing">

                <div class="account-content">
                    <div class="scrollspy-example" data-spy="scroll" data-target="#account-settings-scroll" data-offset="-100">
                        <div class="row">
                            <div class="col-xl-12 col-lg-12 col-md-12 layout-spacing">
                                <form id="add_page" action="{{route('service.store')}}" method="post" class="section general-info" enctype="multipart/form-data">
                                  @csrf
                                  @method('POST')
                                    <div class="info">
                                        <h6 class="">Page Information</h6>
                                        <div class="row">
                                            <div class="col-lg-11 mx-auto">
                                                <div class="row">
                                                    <div class="col-xl-2 col-lg-12 col-md-4">
                                                        <div class="upload mt-4 pr-md-4">
                                                            <input type="file" id="input-file-max-fs" class="dropify" data-default-file="assets/img/200x200.jpg" data-max-file-size="2M" / name="image" required accept="image/*">
                                                           <small style="text-align: center;">Upload Image</small>
                                                        </div>
                                                    </div>
                                                </div> 

                                                 <div class="row" style="margin-top: 30px;">
                                                    <div class="col-xl-4 col-lg-12 col-md-4">
                                                         <div class="form-group">
                                                            <label for="fullName">Primary Category</label>
                                                            <select type="text" class="form-control" name="primary_id" id="primary_id" required >
                                                            <option value="">Select Primary Category</option>
                                                            @foreach($primary_categorys as $primary)
                                                                <option value="{{$primary->id}}">{{$primary->title}}</option>
                                                            @endforeach
                                                          </select>
                                                        </div>
                                                    </div>

                                                    <div class="col-xl-4 col-lg-12 col-md-4">
                                                         <div class="form-group">
                                                            <label for="fullName">Parent Category</label>
                                                            <select type="text" class="form-control" name="parent_id" id="parent_id" required>
                                                                <option value="">--Select Parent Category--</option>
                                                            </select>
                                                        </div>
                                                    </div>

                                                    <div class="col-xl-4 col-lg-12 col-md-4">
                                                         <div class="form-group">
                                                            <label for="fullName">Child Category</label>
                                                            <select type="text" class="form-control" name="child_id" id="child_id" required>
                                                                <option value="">--Select Child Category--</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div> 
                                                <div class="row"> 

                                                     <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <label for="fullName">Meta Tag</label>
                                                            <input type="text" class="form-control mb-4" placeholder="Enter Meta Tag" name="meta_tag"  required="">
                                                        </div>
                                                    </div>
                                                     <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <label for="fullName">Meta Description</label>
                                                            <input type="text" class="form-control mb-4" placeholder="Enter Meta Description" name="meta_description"  required="">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12">
                                                        <div class="form-group">
                                                            <label for="fullName">Page Name<span style="color: red;">*</span></label>
                                                            <input type="text" class="form-control mb-4" id="fullName" placeholder="Page Name" name="name"  required="">
                                                        </div>
                                                    </div>

                                                    <div class="col-sm-12">
                                                        <div class="form-group">
                                                            <label for="aboutBio">Page Content<span style="color: red;">*</span></label>
                                                            <textarea class="form-control" id="aboutBio" placeholder="Write Content for Page" rows="25" name="content" required=""></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
      <!--  END CONTENT AREA  -->


@endsection

techosoft/resources/views/admin/services/index.blade.php
@extends('layouts.app')
@section('title', 'CMS Mangement')
@section('breadcrumb')
    <!--  BEGIN NAVBAR  -->
    <div class="sub-header-container">
        <header class="header navbar navbar-expand-sm">
            <a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg></a>

            <ul class="navbar-nav flex-row">
                <li>
                    <div class="page-header">

                        <nav class="breadcrumb-one" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                              <li class="breadcrumb-item"><a href="javascript:void(0);">CMS Management</a></li>
                              <li class="breadcrumb-item"><a href="javascript:void(0);">Services Page List</a></li>
                            </ol>
                        </nav>


                    </div>
                </li>  
            </ul>
            <ul class="navbar-nav flex-row ml-auto ">
                <li class="nav-item more-dropdown">
                    <div class="dropdown  custom-dropdown-icon">
                        <div class="col-lg-12">
                          <a  href="{{route('service.create')}}"><span  class="btn btn-outline-success mb-2">Add Service Page</span></a>
                        </div>
                    </div>
                </li>
            </ul>
        </header>
    </div>
    <!--  END NAVBAR  -->

@endsection

@section('content')
  <div class="layout-px-spacing">            
      <div class="row layout-top-spacing">
          <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
              <div class="widget-content widget-content-area br-6">
                  <div class="table-responsive mb-4 mt-4">
                      <table id="alter_pagination" class="table table-hover" style="width:100%">
                          <thead>
                              <tr>
                                  <th>Sr no.</th>
                                  <th>Image</th>
                                  <th>Title</th>
                                  <th>Content</th>
                                  <th>Status</th>
                                  <th>Action</th>
                                  
                              </tr>
                          </thead>
                          <tbody>
                              @php $count=1; @endphp
                                @foreach($services as $data)
                              <tr>
                                <td>{{$count++}}</td>
                                <td>
                                   <img  src="{{URL::TO('img/service/'. $data->image)}}" style="   object-fit: scale-down;
                                        position: relative;
                                        height: 54px;
                                        width: 75px;
                                        padding: 1px;">    
                                </td>
                                <td>{{$data->title}}</td>
                                <td>{{substr($data->content,0,60)}}</td>
                                <td>
                                    @if(is_null($data->deleted_at))
                                       <span><strong>Active</strong></span>
                                    @else
                                       <span style="color: red;"><strong>Inactive</strong></span>
                                    @endif
                                </td>
                                <td>
                                  <a href="{{route('service.show',$data->id)}}"><i data-feather="edit" style="color: blue; margin-right:5px;"  ></i></a>

                                  <a class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Status" href="{{route('service.edit',$data->id)}}">
                                    @if(is_null($data->deleted_at))
                                       <i data-feather="toggle-right" style="color: green;"></i>
                                    @else
                                       <i data-feather="toggle-left" style="color: red;"></i>
                                    @endif
                                  </a>
                                </td>
                              </tr>
                              @endforeach
                           
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
      </div>
  </div>

@endsection