techosoft/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

/*USER MANAGEMENT*/
// Route::resource('/clients', 'Admin\User\UserController');
Route::resource('/staff', 'Admin\User\StaffController');
Route::resource('/client', 'Admin\User\ClientController');

/*CATEGORY MANAGEMENT*/
Route::resource('/primary', 'Admin\Category\PrimaryController');
Route::resource('/parent', 'Admin\Category\ParentController');
Route::resource('/child', 'Admin\Category\ChildController');
Route::get('/child/get_parent/{id}','Admin\Category\ChildController@get_parent');
/*END CATEGORY*/

/*SITE CONFIG*/
Route::resource('/settings', 'Admin\Setting\SettingController');

/*PAGE MANAGEMENT*/
Route::resource('/page', 'Admin\Page\PageController');

/*PAGE MANAGEMENT*/
Route::resource('/service', 'Admin\Services\ServiceController');
Route::get('get/child/{id}','Admin\Services\ServiceController@get_child');

/*PROJECT MANAGEMENT*/
Route::resource('techosoft_service', 'Admin\Project\ServiceController');
Route::resource('project', 'Admin\Project\ProjectController');
Route::get('project/add_new_phase/{id}', 'Admin\Project\ProjectController@add_new_phase');
Route::post('project/store_new_phase/{id}', 'Admin\Project\ProjectController@store_new_phase');
Route::get('change/status/{id}/{status}', 'Admin\Project\ProjectController@update_status');
Route::get('edit_phase/{phase_id}', 'Admin\Project\ProjectController@edit_phase');
Route::get('delete/doc/{id}', 'Admin\Project\ProjectController@delete_doc');

/*ORDER MANAGEMENT*/
Route::resource('order', 'Admin\Order\OrderController');

/*BILL MANAGEMENT*/
Route::resource('bill', 'Admin\Bill\BillController');
Route::get('ajax/get/order_id/{id}', 'Admin\Bill\BillController@get_order');



/*Dark mode route*/
Route::get('/darkmode/status', 'Other\CommonController@darkmode')->name('darkmode.status');














// COURSE MANAGEMENT
Route::get('/step_first', 'Admin\Course\CourseController@step_first')->name('step_first');
Route::get('/upload/course', 'Admin\Course\CourseController@upload_course')->name('upload_course');

techosoft/resources/views/admin/pages/create.blade.php
@extends('layouts.app')
@section('title', 'CMS')
@section('breadcrumb')
	  <!--  BEGIN NAVBAR  -->
    <div class="sub-header-container">
        <header class="header navbar navbar-expand-sm">
            <a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg></a>

            <ul class="navbar-nav flex-row">
                <li>
                    <div class="page-header">

                        <nav class="breadcrumb-one" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0);"> CMS Management</a></li>
                                <li class="breadcrumb-item"><a href="javascript:void(0);"> Other Page</a></li>
                                <li class="breadcrumb-item"><a href="javascript:void(0);">Create New Page</a></li>
                            </ol>
                        </nav>


                    </div>
                </li>  
            </ul>
            <ul class="navbar-nav flex-row ml-auto ">
                <li class="nav-item more-dropdown">
                    <div class="dropdown  custom-dropdown-icon">
                        <div class="col-lg-12">
                             <button form="add_page" type="submit" class="btn btn-outline-primary btn-rounded mb-2" value="Submit">Add Page</button>
                        </div>
                    </div>
                </li>
            </ul>
        </header>
    </div>
    <!--  END NAVBAR  -->
    

@endsection

@section('content')


      <!--  BEGIN CONTENT AREA  -->
        <div class="layout-px-spacing">                
                
            <div class="account-settings-container layout-top-spacing">

                <div class="account-content">
                    <div class="scrollspy-example" data-spy="scroll" data-target="#account-settings-scroll" data-offset="-100">
                        <div class="row">
                            <div class="col-xl-12 col-lg-12 col-md-12 layout-spacing">
                                <form id="add_page" action="{{route('page.store')}}" method="post" class="section general-info" enctype="multipart/form-data">
                                  @csrf
                                  @method('POST')
                                    <div class="info">
                                        <h6 class="">Page Information</h6>
                                        <div class="row">
                                            <div class="col-lg-11 mx-auto">
                                                <div class="row">
                                                    <div class="col-xl-2 col-lg-12 col-md-4">
                                                        <div class="upload mt-4 pr-md-4">
                                                            <input type="file" id="input-file-max-fs" class="dropify" data-default-file="assets/img/200x200.jpg" data-max-file-size="2M" / name="image" required accept="image/*">
                                                           <small style="text-align: center;">Upload Image</small>
                                                        </div>
                                                    </div>
                                                   
                                                </div> 
                                                <div class="row" style="margin-top: 20px;"> 

                                                     <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <label for="fullName">Meta Tag</label>
                                                            <input type="text" class="form-control mb-4" id="fullName" placeholder="Enter Meta Tag" name="meta_tag"  required="">
                                                        </div>
                                                    </div>
                                                     <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <label for="fullName">Meta Description</label>
                                                            <input type="text" class="form-control mb-4" id="fullName" placeholder="Enter Meta Description" name="meta_description"  required="">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12">
                                                        <div class="form-group">
                                                            <label for="fullName">Page Name<span style="color: red;">*</span></label>
                                                            <input type="text" class="form-control mb-4" id="fullName" placeholder="Page Name" name="name"  required="">
                                                        </div>
                                                    </div>

                                                    <div class="col-sm-12">
                                                        <div class="form-group">
                                                            <label for="aboutBio">Page Content<span style="color: red;">*</span></label>
                                                            <textarea class="form-control" id="aboutBio" placeholder="Write Content for Page" rows="25" name="content" required=""></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
      <!--  END CONTENT AREA  -->


@endsection

techosoft/resources/views/admin/pages/edit.blade.php
@extends('layouts.app')
@section('title', 'CMS')
@section('breadcrumb')
	  <!--  BEGIN NAVBAR  -->
    <div class="sub-header-container">
        <header class="header navbar navbar-expand-sm">
            <a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg></a>

            <ul class="navbar-nav flex-row">
                <li>
                    <div class="page-header">

                        <nav class="breadcrumb-one" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0);"> CMS Management</a></li>
                                <li class="breadcrumb-item"><a href="javascript:void(0);"> Page Management</a></li>
                                <li class="breadcrumb-item"><a href="javascript:void(0);">Edit Page</a></li>
                            </ol>
                        </nav>


                    </div>
                </li>  
            </ul>
            <ul class="navbar-nav flex-row ml-auto ">
                <li class="nav-item more-dropdown">
                    <div class="dropdown  custom-dropdown-icon">
                        <div class="col-lg-12">
                             <button form="add_page" type="submit" class="btn btn-outline-primary btn-rounded mb-2" value="Submit">Update Details</button>
                        </div>
                    </div>
                </li>
            </ul>
        </header>
    </div>
    <!--  END NAVBAR  -->
    

@endsection

@section('content')


      <!--  BEGIN CONTENT AREA  -->
        <div class="layout-px-spacing">                
                
            <div class="account-settings-container layout-top-spacing">

                <div class="account-content">
                    <div class="scrollspy-example" data-spy="scroll" data-target="#account-settings-scroll" data-offset="-100">
                        <div class="row">
                            <div class="col-xl-12 col-lg-12 col-md-12 layout-spacing">
                                <form id="add_page" action="{{route('page.update', $page->id)}}" method="post" class="section general-info" enctype="multipart/form-data">
                                  @csrf
                                  @method('PUT')
                                    <div class="info">
                                        <h6 class="">Page Information</h6>
                                        <div class="row">
                                            <div class="col-lg-11 mx-auto">
                                                <div class="row">
                                                    <div class="col-xl-2 col-lg-12 col-md-4">
                                                        <div class="upload mt-4 pr-md-4">
                                                            <input type="file" id="input-file-max-fs" class="dropify" data-default-file="{{URL::TO('img/page/'. $page->image)}}" data-max-file-size="2M" / name="image" accept="image/*">
                                                           <small style="text-align: center;">Upload Image</small>
                                                        </div>
                                                    </div>
                                                   
                                                </div> 
                                                <div class="row" style="margin-top: 20px;"> 

                                                      <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <label for="fullName">Meta Tag</label>
                                                            <input type="text" class="form-control mb-4" id="fullName" placeholder="Enter Meta Tag" name="meta_tag"  value="{{$page->meta_tag}}">
                                                        </div>
                                                    </div>
                                                     <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <label for="fullName">Meta Description</label>
                                                            <input type="text" class="form-control mb-4" id="fullName" placeholder="Enter Meta Description" name="meta_description"  value="{{$page->meta_description}}">
                                                        </div>
                                                    </div>

                                                    <div class="col-sm-12">
                                                        <div class="form-group">
                                                            <label for="fullName">Name <span style="color: red;">*</span></label>
                                                            <input type="text" class="form-control mb-4" id="fullName" placeholder="Full Name" name="name"  required="" value="{{$page->title}}">
                                                        </div>
                                                    </div>

                                                    <div class="col-sm-12">
                                                        <div class="form-group">
                                                            <label for="aboutBio">Page Content</label>
                                                            <textarea class="form-control" id="aboutBio" placeholder="Write Content of Page" rows="25" name="content" required="">{{$page->content}}
                                                            </textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
      <!--  END CONTENT AREA  -->


@endsection

techosoft/resources/views/admin/pages/index.blade.php
@extends('layouts.app')
@section('title', 'User Mangement')
@section('breadcrumb')
    <!--  BEGIN NAVBAR  -->
    <div class="sub-header-container">
        <header class="header navbar navbar-expand-sm">
            <a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg></a>

            <ul class="navbar-nav flex-row">
                <li>
                    <div class="page-header">

                        <nav class="breadcrumb-one" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                              <li class="breadcrumb-item"><a href="javascript:void(0);">CMS Management</a></li>
                              <li class="breadcrumb-item"><a href="javascript:void(0);">Page List</a></li>
                            </ol>
                        </nav>


                    </div>
                </li>  
            </ul>
            <ul class="navbar-nav flex-row ml-auto ">
                <li class="nav-item more-dropdown">
                    <div class="dropdown  custom-dropdown-icon">
                        <div class="col-lg-12">
                          <a  href="{{route('page.create')}}"><span  class="btn btn-outline-success mb-2">Add New Pages</span></a>
                        </div>
                    </div>
                </li>
            </ul>
        </header>
    </div>
    <!--  END NAVBAR  -->

@endsection

@section('content')
  <div class="layout-px-spacing">            
      <div class="row layout-top-spacing">
          <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
              <div class="widget-content widget-content-area br-6">
                  <div class="table-responsive mb-4 mt-4">
                      <table id="alter_pagination" class="table table-hover" style="width:100%">
                          <thead>
                              <tr>
                                  <th>Sr no.</th>
                                  <th>Image</th>
                                  <th>Title</th>
                                  <th>Content</th>
                                  <th>Status</th>
                                  <th>Action</th>
                                  
                              </tr>
                          </thead>
                          <tbody>
                              @php $count=1; @endphp
                                @foreach($pages as $data)
                              <tr>
                                <td>{{$count++}}</td>
                                <td>
                                   <img  src="{{URL::TO('img/page/'. $data->image)}}" style="   object-fit: scale-down;
                                        position: relative;
                                        height: 54px;
                                        width: 75px;
                                        padding: 1px;">    
                                </td>
                                <td>{{$data->title}}</td>
                                <td>{{substr($data->content,0,60)}}</td>
                                <td>
                                    @if(is_null($data->deleted_at))
                                       <span><strong>Active</strong></span>
                                    @else
                                       <span style="color: red;"><strong>Inactive</strong></span>
                                    @endif
                                </td>
                                <td>
                                  <a href="{{route('page.show',$data->id)}}"><i data-feather="edit" style="color: blue; margin-right:5px;"  ></i></a>

                                  <a class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Status" href="{{route('page.edit',$data->id)}}">
                                    @if(is_null($data->deleted_at))
                                       <i data-feather="toggle-right" style="color: green;"></i>
                                    @else
                                       <i data-feather="toggle-left" style="color: red;"></i>
                                    @endif
                                  </a>
                                </td>
                              </tr>
                              @endforeach
                           
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
      </div>
  </div>

@endsection