techosoft/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

/*USER MANAGEMENT*/
// Route::resource('/clients', 'Admin\User\UserController');
Route::resource('/staff', 'Admin\User\StaffController');
Route::resource('/client', 'Admin\User\ClientController');

/*CATEGORY MANAGEMENT*/
Route::resource('/primary', 'Admin\Category\PrimaryController');
Route::resource('/parent', 'Admin\Category\ParentController');
Route::resource('/child', 'Admin\Category\ChildController');
Route::get('/child/get_parent/{id}','Admin\Category\ChildController@get_parent');
/*END CATEGORY*/

/*SITE CONFIG*/
Route::resource('/settings', 'Admin\Setting\SettingController');

/*PAGE MANAGEMENT*/
Route::resource('/page', 'Admin\Page\PageController');

/*PAGE MANAGEMENT*/
Route::resource('/service', 'Admin\Services\ServiceController');
Route::get('get/child/{id}','Admin\Services\ServiceController@get_child');

/*PROJECT MANAGEMENT*/
Route::resource('techosoft_service', 'Admin\Project\ServiceController');
Route::resource('project', 'Admin\Project\ProjectController');
Route::get('project/add_new_phase/{id}', 'Admin\Project\ProjectController@add_new_phase');
Route::post('project/store_new_phase/{id}', 'Admin\Project\ProjectController@store_new_phase');
Route::get('change/status/{id}/{status}', 'Admin\Project\ProjectController@update_status');
Route::get('edit_phase/{phase_id}', 'Admin\Project\ProjectController@edit_phase');
Route::get('delete/doc/{id}', 'Admin\Project\ProjectController@delete_doc');

/*ORDER MANAGEMENT*/
Route::resource('order', 'Admin\Order\OrderController');

/*BILL MANAGEMENT*/
Route::resource('bill', 'Admin\Bill\BillController');
Route::get('ajax/get/order_id/{id}', 'Admin\Bill\BillController@get_order');



/*Dark mode route*/
Route::get('/darkmode/status', 'Other\CommonController@darkmode')->name('darkmode.status');














// COURSE MANAGEMENT
Route::get('/step_first', 'Admin\Course\CourseController@step_first')->name('step_first');
Route::get('/upload/course', 'Admin\Course\CourseController@upload_course')->name('upload_course');

techosoft/app/Http/Controllers/Admin/Category/ChildController.php
<?php

namespace App\Http\Controllers\Admin\Category;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Category\Primary;
use App\Model\Category\Parent_cat;
use App\Model\Category\Child;
use Session;

class ChildController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Parent_cat::withTrashed()->where('deleted_at', '!=', '')->get();
        $delete_id = array();
        foreach($data as $id){
            $delete_id[] = $id->id;
        }

        $primary_category = Primary::all();
        $child_categorys   = Child::withTrashed()->whereNotIn('parent_id', $delete_id)->get();
        return view('admin.category.child', compact('primary_category', 'child_categorys'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
                            'primary_id'  => 'required',
                            'parent_id'   => 'required',
                            'title'       => 'required',
                            'image'       => 'required',
                            'description' => 'required',
                            ]);
      
        $image = $request->image;
        $image_name  =strtotime(date('Y-m-d H:i:s')).'_'.$image->getClientOriginalName();
        $image->move('img/category', $image_name);

            $insert = Child::create([
                'primary_id'     => $request->primary_id,
                'parent_id'      => $request->parent_id,
                'title'          => $request->title,
                'image'          => $image_name, 
                'description'    => $request->description,
        ]);
        Session::flash('success',$request->title. ' Child Category Added Successfully');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) 
    {
        $primary_category = Primary::all();
        $data= Child::where('id', $id)->first();
        return view('admin.category.edit_child', compact('primary_category','data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $get_Child_category = Child::where('id',$id)->withTrashed()->first();

        if(is_null($get_Child_category->deleted_at)){
            $delete = Child::where('id',$id)->delete();
        }
        else{
            $restore = Child::where('id', $id)->restore();
        }
        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
                        'primary_id'  => 'required',
                        'parent_id'  => 'required',
                        'title'       => 'required',
                        'description' => 'required',
                        ]);
       
        if(isset($request->image)){

            $check_image = Child::where('id', $id)->first();
            $image_path = 'img/category/'.$check_image->image;
            if(file_exists($image_path)){
              unlink($image_path);
            }
            $image = $request->image;
            $image_name  =strtotime(date('Y-m-d H:i:s')).'_'.$image->getClientOriginalName();
            $image->move('img/category', $image_name);
           
            $update = Child::where('id', $id)->update([
                                    'primary_id'     => $request->primary_id,
                                    'parent_id'      => $request->parent_id,
                                    'title'          => $request->title,
                                    'image'          => $image_name, 
                                    'description'    => $request->description,
                                 ]);
        }
        else{
            $update = Child::where('id', $id)->update([
                                    'primary_id'     => $request->primary_id,
                                    'parent_id'      => $request->parent_id,
                                    'title'          => $request->title,
                                    'description'    => $request->description,
                                 ]);

        }

        Session::flash('success',$request->title. ' Child Category Updated Successfully');
        return redirect()->route('child.index');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function get_parent($id){
        $data = Parent_cat::where('primary_id', $id)->get()->pluck('title', 'id');
        return Response()->json($data);
    }
}

techosoft/app/Http/Controllers/Admin/Category/ParentController.php
<?php

namespace App\Http\Controllers\Admin\Category;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Category\Primary;
use App\Model\Category\Parent_cat;
use Session;

class ParentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Primary::withTrashed()->where('deleted_at', '!=', '')->get();
        $delete_id = array();
        foreach($data as $id){
            $delete_id[] = $id->id;
        }

        $primary_category = Primary::all();
        $parent_category = Parent_cat::withTrashed()->whereNotIn('primary_id', $delete_id)->get();
        // dd($parent_category);
        return view('admin.category.parent', compact('parent_category', 'primary_category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
                            'primary_id'  => 'required',
                            'title'       => 'required',
                            'image'       => 'required',
                            'description' => 'required',
                            ]);
      
        $image = $request->image;
        $image_name  =strtotime(date('Y-m-d H:i:s')).'_'.$image->getClientOriginalName();
        $image->move('img/category', $image_name);

            $insert = Parent_cat::create([
                'primary_id'     => $request->primary_id,
                'title'          => $request->title,
                'image'          => $image_name, 
                'description'    => $request->description,
        ]);
        Session::flash('success',$request->title. ' Parent Category Added Successfully');
        return back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $primary_category = Primary::all();
        $data = Parent_cat::where('id',$id)->first();
        return view('admin.category.edit_parent', compact('data', 'primary_category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $get_Parent_cat_category = Parent_cat::where('id',$id)->withTrashed()->first();

        if(is_null($get_Parent_cat_category->deleted_at)){
            $delete = Parent_cat::where('id',$id)->delete();
        }
        else{
            $restore = Parent_cat::where('id', $id)->restore();
        }
        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());    
       $request->validate([
                        'primary_id'  => 'required',
                        'title'       => 'required',
                        'description' => 'required',
                        ]);

        if(isset($request->image)){

            $check_image = Parent_cat::where('id', $id)->first();
            $image_path = 'img/category/'.$check_image->image;
            if(file_exists($image_path)){
              unlink($image_path);
            }
            $image = $request->image;
            $image_name  =strtotime(date('Y-m-d H:i:s')).'_'.$image->getClientOriginalName();
            $image->move('img/category', $image_name);

            $update = Parent_cat::where('id', $id)->update([
                                    'primary_id'     => $request->primary_id,
                                    'title'          => $request->title,
                                    'image'          => $image_name, 
                                    'description'    => $request->description,
                                 ]);
        }
        else{
            $update = Parent_cat::where('id', $id)->update([
                                    'primary_id'     => $request->primary_id,
                                    'title'          => $request->title,
                                    'description'    => $request->description,
                                 ]);

        }

        Session::flash('success',$request->title. 'Parent Category Updated Successfully');
        return redirect()->route('parent.index');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

techosoft/app/Http/Controllers/Admin/Category/PrimaryController.php
<?php

namespace App\Http\Controllers\Admin\Category;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Category\Primary;
use Session;

class PrimaryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Primary::all();
        // dd($data);
        $primary_category = Primary::withTrashed()->paginate(5);
        return view('admin.category.primary', compact('primary_category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
     //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['title'=>'required']);

        $insert = Primary::create(['title'=> $request->title]);
        Session::flash('success','Primary Category Added Successfully');
        return back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        // DELTE METHOD CALL IN THIS FUNCTION
        $get_primary_category = Primary::where('id',$id)->withTrashed()->first();

        if(is_null($get_primary_category->deleted_at)){
            $delete = Primary::where('id',$id)->delete();
        }
        else{
            $restore = Primary::where('id', $id)->restore();
        }
        return back();
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $find = Primary::find($id);
        if($find->status == 1){
            $find->status = 0;
            $find->save();
        }
        else{
            $find->status =1;
            $find->save();
        }
        Session::flash('success',$find->title.' Status Changed Successfully');
        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(['title'=>'required']);

        $update = Primary::where('id',$id)->update(['title'=> $request->title]);
        Session::flash('success','Primary Category Updated Successfully');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

techosoft/resources/views/admin/category/parent.blade.php
@extends('layouts.app')
@section('title', 'User Mangement')
@section('breadcrumb')
    <!--  BEGIN NAVBAR  -->
    <div class="sub-header-container">
        <header class="header navbar navbar-expand-sm">
            <a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg></a>

            <ul class="navbar-nav flex-row">
                <li>
                    <div class="page-header">

                        <nav class="breadcrumb-one" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0);">Category Management</a></li>
                                  <li class="breadcrumb-item"><a href="javascript:void(0);">Parent Category</a></li>
                            </ol>
                        </nav>


                    </div>
                </li>  
            </ul>
            <ul class="navbar-nav flex-row ml-auto ">
                <li class="nav-item more-dropdown">
                    <div class="dropdown  custom-dropdown-icon">
                        <div class="col-lg-12">
                            <!-- Fade in down modal -->
                          <a  data-toggle="modal" data-target="#create_primary_model"><span  class="btn btn-outline-primary mb-2">Add Parent Category</span></a>
                        </div>
                    </div>
                </li>
            </ul>
        </header>
    </div>
    <!--  END NAVBAR  -->

    <!-- BEGIN ADD PRIMARY CATEGORY MODEL -->
    <div class="modal fade" id="create_primary_model" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
       <div class="modal-dialog" role="document">
          <div class="modal-content">
             <form  action="{{route('parent.store')}}" method="post" enctype="multipart/form-data">
             @csrf
             @method('post')
                <div class="modal-header">
                   <h5 class="modal-title" id="exampleModalLabel">Add Parent Category</h5>
                   <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                   </button>
                </div>
                <div class="modal-body">
                    <div class="form-group mb-3">
                      <label>Primary Category</label>
                      <select type="text" class="form-control" name="primary_id" aria-describedby="emailHelp1" placeholder="Primary Category" required>
                          <option value="">Select Primary Category</option>
                          @foreach($primary_category as $row)
                             <option value="{{$row->id}}">{{$row->title}}</option>
                          @endforeach
                      </select>
                    </div>

                    <div class="form-group mb-3">
                      <label>Parent Category</label>
                        <input type="text" class="form-control" name="title" aria-describedby="emailHelp1" placeholder="Title" required="">
                    </div>

                    <div class="form-group mb-3">
                        <label>Description</label>
                        <textarea type="text" class="form-control" name="description"  aria-describedby="emailHelp1" rows="5" placeholder="Write Desctiption" required=""></textarea>
                    </div>

                   <div class=" form-group  mb-3 col-xl-6 col-lg-12 col-md-4" style="margin-left: -15px!important;">
                        <div class="upload mt-4 pr-md-4">
                          <label>Upload Picture</label>
                            <input type="file" id="input-file-max-fs" class="dropify" data-default-file="" data-max-file-size="2M" / name="image" required="" accept="image/*">
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                   <button class="btn" data-dismiss="modal"><i class="flaticon-cancel-12"></i> Discard</button>
                   <button type="submit" class="btn btn-primary">Update</button>
                </div>
             </form>
          </div>
       </div>
    </div>
    <!-- END MODEL -->

@endsection

@section('content')
  <div class="layout-px-spacing">            
      <div class="row layout-top-spacing">
          <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
              <div class="widget-content widget-content-area br-6">
                  <div class="table-responsive mb-4 mt-4">
                      <table id="alter_pagination" class="table table-hover" style="width:100%">
                          <thead>
                              <tr>
                                  <th>Sr no.</th>
                                  <th>Image</th>
                                  <th>Primary Category</th>
                                  <th>Parent Title</th>
                                  <th>Status</th>
                                  <th>Action</th>
                                  
                              </tr>
                          </thead>
                          <tbody>
                              @php $count=1; @endphp
                                @foreach($parent_category as $data)
                              <tr>
                                <td>{{$count++}}</td>
                                <td>
                                  <img  src="{{URL::TO('img/category/'. $data->image)}}" style="    object-fit: scale-down;
                                        position: relative;
                                        height: 54px;
                                        width: 75px;
                                        padding: 1px;">    
                                </td>
                                <td>{{$data->primary->title}}</td>
                                <td>{{$data->title}}</td>
                                <td>
                                    @if(is_null($data->deleted_at))
                                       <span><strong>Active</strong></span>
                                    @else
                                       <span style="color: red;"><strong>Inactive</strong></span>
                                    @endif
                                </td>
                                <td>
                                  <a href="{{route('parent.show',$data->id)}}"><i data-feather="edit" style="color: blue; margin-right:5px;"  ></i></a>

                                  <a class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Status" href="{{route('parent.edit',$data->id)}}">
                                    @if(is_null($data->deleted_at))
                                       <i data-feather="toggle-right" style="color: green;"></i>
                                    @else
                                       <i data-feather="toggle-left" style="color: red;"></i>
                                    @endif
                                  </a>

                                </td>
                              </tr>
                              @endforeach
                           
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
      </div>
  </div>

@endsection

techosoft/resources/views/admin/category/primary.blade.php
@extends('layouts.app')
@section('title', 'User Mangement')
@section('breadcrumb')
	  <!--  BEGIN NAVBAR  -->
    <div class="sub-header-container">
        <header class="header navbar navbar-expand-sm">
            <a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg></a>

            <ul class="navbar-nav flex-row">
                <li>
                    <div class="page-header">

                        <nav class="breadcrumb-one" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0);"> Category Management</a></li>
                                  <li class="breadcrumb-item"><a href="javascript:void(0);">Primary Category</a></li>
                            </ol>
                        </nav>


                    </div>
                </li>  
            </ul>
        </header>
    </div>
    <!--  END NAVBAR  -->
    

@endsection

@section('content')

<div class="main-content">
   <div class="col-12">
      <div class="container">
         <div class="row">
            <div id="flStackForm" class="col-md-4 layout-spacing layout-top-spacing">
               <div class="statbox widget box box-shadow">
                  <div class="widget-header">
                     <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                           <h4>Add Primary Category</h4>
                        </div>
                     </div>
                  </div>
                  <div class="widget-content widget-content-area">
                     <form method="post" action="{{route('primary.store')}}" method="post">
                        @csrf
                        @method('POST')
                        <div class="form-group mb-3">
                           <input type="text" class="form-control" name="title" id="tite" aria-describedby="emailHelp1" placeholder="Primary Category Name">
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Submit</button>
                     </form>
                  </div>
               </div>
            </div>

            <div id="flStackForm" class="col-md-8 layout-spacing layout-top-spacing">
               <div class="statbox widget box box-shadow">
                  <div class="widget-header">
                     <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                           <h4>Primary Categories List</h4>
                        </div>
                     </div>
                  </div>
                  <div class="widget-content widget-content-area">
                     <table id="zero-config" class="table table-hover" style="width:100%">
                        <thead>
                           <tr>
                              <th>Sr no.</th>
                              <th>Primary Title</th>
                              <th>Status</th>
                              <th>Action</th>
                           </tr>
                        </thead>
                        <tbody>
                                @php $count=1; @endphp
                                @foreach($primary_category as $data)
                            <tr>
                                <td>{{$count++}}</td>
                                <td>{{$data->title}}</td>
                                <td>
                                    @if(is_null($data->deleted_at))
                                       <span><strong>Active</strong></span>
                                    @else
                                       <span style="color: red;"><strong>Inactive</strong></span>
                                    @endif
                                </td>
                                <td>
                                 <a  data-toggle="modal" data-target="#primary{{$data->id}}"><i data-feather="edit" style="color: blue; margin-right:5px;"></i></a>

                                <!--  <a class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Status" href="{{route('primary.edit',$data->id)}}"><i data-feather="power" style="color: yellow; margin-right:5px;" ></i></a> -->

                                  <a class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" href="{{route('primary.show',$data->id)}}" data-confirm="Are you sure you want to delete this?">
                                    @if(is_null($data->deleted_at))
                                       <i data-feather="toggle-right" style="color: green;"></i>
                                    @else
                                       <i data-feather="toggle-left" style="color: red;"></i>
                                    @endif

                                  </a>


                                </td>

                              <!-- Modal -->
                              <div class="modal fade" id="primary{{$data->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                 <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                       <form method="post" action="{{route('primary.update',$data->id)}}">
                                          <div class="modal-header">
                                             <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                             </button>
                                          </div>
                                          <div class="modal-body">
                                             @csrf
                                             @method('put')
                                             <div class="form-group mb-3">
                                                <input type="text" class="form-control" name="title" id="title" aria-describedby="emailHelp1" value="{{$data->title}}">
                                             </div>
                                          </div>
                                          <div class="modal-footer">
                                             <button class="btn" data-dismiss="modal"><i class="flaticon-cancel-12"></i> Discard</button>
                                             <button type="submit" class="btn btn-primary">Update</button>
                                          </div>
                                       </form>
                                    </div>
                                 </div>
                              </div>
                           </tr>
                          @endforeach
                        </tbody>
                     </table>
                     <div style="position: relative;margin-left: 40%;margin-right: 50%;">
                        {{ $primary_category->links() }}
                    </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

@endsection